# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [33]:
# Dependencies and Setup
import ipywidgets as widgets
import sys
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
!pip install gmaps
import gmaps
import gmaps.datasets
import os
# Import API key
from api_keys import g_key

Requirement already satisfied: gmaps in c:\users\kaleb\anaconda3\lib\site-packages (0.9.0)
Requirement already satisfied: six in c:\users\kaleb\anaconda3\lib\site-packages (from gmaps) (1.15.0)
Requirement already satisfied: ipython>=5.3.0 in c:\users\kaleb\anaconda3\lib\site-packages (from gmaps) (7.16.1)
Requirement already satisfied: geojson>=2.0.0 in c:\users\kaleb\anaconda3\lib\site-packages (from gmaps) (2.5.0)
Requirement already satisfied: ipywidgets>=7.0.0 in c:\users\kaleb\anaconda3\lib\site-packages (from gmaps) (7.5.1)
Requirement already satisfied: traitlets>=4.3.0 in c:\users\kaleb\anaconda3\lib\site-packages (from gmaps) (4.3.3)
Requirement already satisfied: decorator in c:\users\kaleb\anaconda3\lib\site-packages (from ipython>=5.3.0->gmaps) (4.4.2)
Requirement already satisfied: pygments in c:\users\kaleb\anaconda3\lib\site-packages (from ipython>=5.3.0->gmaps) (2.6.1)
Requirement already satisfied: pickleshare in c:\users\kaleb\anaconda3\lib\site-packages (from ipython>=5.3.0->gmaps) (0.7.5)
Requirement already satisfied: jedi>=0.10 in c:\users\kaleb\anaconda3\lib\site-packages (from ipython>=5.3.0->gmaps) (0.17.1)
Requirement already satisfied: setuptools>=18.5 in c:\users\kaleb\anaconda3\lib\site-packages (from ipython>=5.3.0->gmaps) (49.2.0.post20200714)
Requirement already satisfied: colorama; sys_platform == "win32" in c:\users\kaleb\anaconda3\lib\site-packages (from ipython>=5.3.0->gmaps) (0.4.3)
Requirement already satisfied: backcall in c:\users\kaleb\anaconda3\lib\site-packages (from ipython>=5.3.0->gmaps) (0.2.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\kaleb\anaconda3\lib\site-packages (from ipython>=5.3.0->gmaps) (3.0.5)
Requirement already satisfied: widgetsnbextension~=3.5.0 in c:\users\kaleb\anaconda3\lib\site-packages (from ipywidgets>=7.0.0->gmaps) (3.5.1)
Requirement already satisfied: nbformat>=4.2.0 in c:\users\kaleb\anaconda3\lib\site-packages (from ipywidgets>=7.0.0->gmaps) (5.0.7)
Requirement already satisfied: ipykernel>=4.5.1 in c:\users\kaleb\anaconda3\lib\site-packages (from ipywidgets>=7.0.0->gmaps) (5.3.2)
Requirement already satisfied: ipython-genutils in c:\users\kaleb\anaconda3\lib\site-packages (from traitlets>=4.3.0->gmaps) (0.2.0)
Requirement already satisfied: parso<0.8.0,>=0.7.0 in c:\users\kaleb\anaconda3\lib\site-packages (from jedi>=0.10->ipython>=5.3.0->gmaps) (0.7.0)
Requirement already satisfied: wcwidth in c:\users\kaleb\anaconda3\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.3.0->gmaps) (0.2.5)
Requirement already satisfied: notebook>=4.4.1 in c:\users\kaleb\anaconda3\lib\site-packages (from widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (6.0.3)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in c:\users\kaleb\anaconda3\lib\site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (3.2.0)
Requirement already satisfied: jupyter-core in c:\users\kaleb\anaconda3\lib\site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (4.6.3)
Requirement already satisfied: jupyter-client in c:\users\kaleb\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (6.1.6)
Requirement already satisfied: tornado>=4.2 in c:\users\kaleb\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (6.0.4)
Requirement already satisfied: terminado>=0.8.1 in c:\users\kaleb\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.8.3)
Requirement already satisfied: Send2Trash in c:\users\kaleb\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.5.0)
Requirement already satisfied: pyzmq>=17 in c:\users\kaleb\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (19.0.1)
Requirement already satisfied: nbconvert in c:\users\kaleb\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (5.6.1)
Requirement already satisfied: prometheus-client in c:\users\kaleb\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.8.0)
Requirement already satisfied: jinja2 in c:\users\kaleb\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (2.11.2)
Requirement already satisfied: attrs>=17.4.0 in c:\users\kaleb\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (19.3.0)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\users\kaleb\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (0.16.0)
Requirement already satisfied: pywin32>=1.0; sys_platform == "win32" in c:\users\kaleb\anaconda3\lib\site-packages (from jupyter-core->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (227)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\kaleb\anaconda3\lib\site-packages (from jupyter-client->ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (2.8.1)
Requirement already satisfied: defusedxml in c:\users\kaleb\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.6.0)
Requirement already satisfied: bleach in c:\users\kaleb\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (3.1.5)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\kaleb\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.4.2)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\users\kaleb\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.8.4)
Requirement already satisfied: entrypoints>=0.2.2 in c:\users\kaleb\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.3)
Requirement already satisfied: testpath in c:\users\kaleb\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.4.4)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\kaleb\anaconda3\lib\site-packages (from jinja2->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.1.1)
Requirement already satisfied: packaging in c:\users\kaleb\anaconda3\lib\site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (20.4)
Requirement already satisfied: webencodings in c:\users\kaleb\anaconda3\lib\site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.5.1)
Requirement already satisfied: pyparsing>=2.0.2 in c:\users\kaleb\anaconda3\lib\site-packages (from packaging->bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (2.4.7)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [19]:
weather_py = r"C:\Users\Kaleb\python-api\output_data\cities.csv"
cities = pd.read_csv(weather_py)
cities.head()

,Unnamed: 0,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,0,nikolskoye,90,RU,1603400985,93,59.70,30.79,9.44,3.00
1,1,busselton,0,AU,1603400966,66,-33.65,115.33,10.00,4.57
2,2,victoria,100,HK,1603400964,46,22.29,114.16,21.67,5.81
3,3,mount gambier,30,GB,1603401006,84,53.66,-1.85,7.78,0.45
4,4,cape town,0,CL,1603400694,24,-36.41,-71.90,26.00,3.10

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [20]:
gmaps.configure(g_key)

In [21]:
cities=cities.rename(columns = {"Max Temp":"MaxTemp", "Wind Speed":"WindSpeed"})
cities["Humidity"].max()

100

In [22]:
locations= cities[["Lat", "Lng"]]
weights=cities["Humidity"]

In [23]:
fig = gmaps.figure()
heat_layer = gmaps.heatmap_layer(
    locations, 
    weights=weights, 
    dissipating=False,
    max_intensity = 100,
    point_radius = 3
)
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [24]:
min_temp= 21.111
max_temp = 26.666
wind_speed = 10
cloudiness = 0

good_cities= cities.query(f"MaxTemp < {max_temp} and MaxTemp > {min_temp} and WindSpeed < {wind_speed} and Cloudiness == {cloudiness}")
good_cities.head()

,Unnamed: 0,City,Cloudiness,Country,Date,Humidity,Lat,Lng,MaxTemp,WindSpeed
4,4,cape town,0,CL,1603400694,24,-36.41,-71.90,26.00,3.10
51,51,salalah,0,OM,1603400991,65,17.02,54.09,26.00,2.60
57,57,gangapur,0,IN,1603401084,38,26.48,76.72,23.14,0.99
78,78,pangkalanbuun,0,ID,1603401045,96,-2.68,111.62,23.51,0.63
104,104,hambantota,0,LK,1603400461,100,6.12,81.12,25.00,3.10

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [25]:
hotel_df = good_cities
hotel_df['Hotel Name']=""
hotel_df.head()

<ipython-input-25-d9cd205f7c86>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hotel_df['Hotel Name']=""

,Unnamed: 0,City,Cloudiness,Country,Date,Humidity,Lat,Lng,MaxTemp,WindSpeed,Hotel Name
4,4,cape town,0,CL,1603400694,24,-36.41,-71.90,26.00,3.10,
51,51,salalah,0,OM,1603400991,65,17.02,54.09,26.00,2.60,
57,57,gangapur,0,IN,1603401084,38,26.48,76.72,23.14,0.99,
78,78,pangkalanbuun,0,ID,1603401045,96,-2.68,111.62,23.51,0.63,
104,104,hambantota,0,LK,1603400461,100,6.12,81.12,25.00,3.10,

In [26]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [27]:
locations["Lat"]= locations["Lat"].astype(str)
locations["Lng"]=locations["Lng"].astype(str)

<ipython-input-27-e18913a566ea>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  locations["Lat"]= locations["Lat"].astype(str)
<ipython-input-27-e18913a566ea>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  locations["Lng"]=locations["Lng"].astype(str)

In [28]:
hotels = pd.DataFrame({"City": hotel_df["City"],
                      "Country": hotel_df["Country"]})
hotels["Hotel Name"]=''
hotels["Lat"]=''
hotels["Lng"]=''

In [29]:
for i,row in locations.iterrows():
    try:
        target_search="Hotel"
        target_radius="5000"
        target_coordinates=["Lat"]+''+row["Lng"]
        base_url= "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
        query_url= f"{url}appid={g_key}&units={units}&q="
        params = { 
        "location": target_coordinates,
        "keyword": target_search,
        "radius": target_radius,
        "key": g_key
        }
        response = requests.get(query_url, params=params).json()
    
        lat = response["results"][0]["geometry"]["location"]["lat"]
        lng = response["results"][0]["geometry"]["location"]["lng"]
        name = response["results"][0]["name"]
    
        hotels.loc[i,"Lat"]=lat
        hotels.loc[i,"Lng"]=lng
        hotels.loc[i,"Hotel Name"]=name
    
        hotel_df.loc[i,"Hotel Name"]=name
    
    except:
        hotels.loc[i,"Hotel Name"]="Hotel not found!"
        hotels.loc[i,"Hotel Name"]="Hotel not found!"

In [30]:
hotels.dropna(inplace=True)
hotels["Date"]=hotel_df["Date"].apply(lambda x: '%.0f' % x)
hotel_df.head(50)

,Unnamed: 0,City,Cloudiness,Country,Date,Humidity,Lat,Lng,MaxTemp,WindSpeed,Hotel Name
4,4,cape town,0,CL,1603400694,24,-36.41,-71.90,26.00,3.10,
51,51,salalah,0,OM,1603400991,65,17.02,54.09,26.00,2.60,
57,57,gangapur,0,IN,1603401084,38,26.48,76.72,23.14,0.99,
78,78,pangkalanbuun,0,ID,1603401045,96,-2.68,111.62,23.51,0.63,
104,104,hambantota,0,LK,1603400461,100,6.12,81.12,25.00,3.10,
143,143,choma,0,ZM,1603401093,39,-16.81,26.95,21.73,2.15,
166,166,saint-pierre,0,RE,1603401095,68,-21.34,55.48,22.00,1.50,
197,197,dromolaxia,0,CY,1603401099,43,34.88,33.59,23.00,3.10,
218,218,gat,0,IL,1603401101,69,31.61,34.76,23.00,2.10,
239,239,bushehr,0,IR,1603401104,53,28.97,50.84,25.00,1.59,
264,264,jati,0,PK,1603401106,35,24.35,68.27,26.56,3.63,
293,293,lichinga,0,MZ,1603401109,43,-13.31,35.24,22.00,4.60,
336,336,sur,0,OM,1603400999,56,22.57,59.53,23.30,2.33,
351,351,beloha,0,MG,1603400995,72,-25.17,45.05,22.02,5.48,
352,352,ormara,0,PK,1603401116,47,25.21,64.64,26.05,1.27,
354,354,saint-joseph,0,RE,1603401116,68,-21.37,55.62,22.00,1.50,
371,371,nampula,0,MZ,1603401119,78,-15.12,39.27,22.00,5.10,
382,382,buraydah,0,SA,1603400965,27,26.33,43.98,23.00,3.60,
410,410,erzin,0,TR,1603401123,79,36.96,36.20,22.78,0.45,
428,428,pilar,0,BR,1603401018,83,-9.60,-35.96,25.00,4.10,
441,441,maceio,0,BR,1603400992,83,-9.67,-35.74,25.00,4.10,
445,445,gasa,0,PS,1603401127,69,31.50,34.47,23.00,2.10,
476,476,rawah,0,IQ,1603401130,35,34.48,41.91,22.52,4.35,
485,485,camp verde,0,OM,1603401131,63,20.67,58.88,25.71,2.67,
501,501,antalaha,0,MG,1603400988,82,-14.90,50.28,21.33,3.41,
509,509,doha,0,QA,1603400673,73,25.29,51.53,25.00,1.50,

In [31]:
hotels.dropna(inplace=True)
hotels.head(50)

              City Country        Hotel Name Lat Lng        Date
4        cape town      CL  Hotel not found!          1603400694
51         salalah      OM  Hotel not found!          1603400991
57        gangapur      IN  Hotel not found!          1603401084
78   pangkalanbuun      ID  Hotel not found!          1603401045
104     hambantota      LK  Hotel not found!          1603400461
143          choma      ZM  Hotel not found!          1603401093
166   saint-pierre      RE  Hotel not found!          1603401095
197     dromolaxia      CY  Hotel not found!          1603401099
218            gat      IL  Hotel not found!          1603401101
239        bushehr      IR  Hotel not found!          1603401104
264           jati      PK  Hotel not found!          1603401106
293       lichinga      MZ  Hotel not found!          1603401109
336            sur      OM  Hotel not found!          1603400999
351         beloha      MG  Hotel not found!          1603400995
352         ormara      PK  Hotel not found!          1603401116
354   saint-joseph      RE  Hotel not found!          1603401116
371        nampula      MZ  Hotel not found!          1603401119
382       buraydah      SA  Hotel not found!          1603400965
410          erzin      TR  Hotel not found!          1603401123
428          pilar      BR  Hotel not found!          1603401018
441         maceio      BR  Hotel not found!          1603400992
445           gasa      PS  Hotel not found!          1603401127
476          rawah      IQ  Hotel not found!          1603401130
485     camp verde      OM  Hotel not found!          1603401131
501       antalaha      MG  Hotel not found!          1603400988
509           doha      QA  Hotel not found!          1603400673

In [32]:
hotel_info = [info_box_template.format(**row) for index, row in hotels.iterrows()]
loca = hotel_df[["Lat", "Lng"]]
weights = good_cities["Humidity"]
markers= gmaps.marker_layer(loca, info_box_content=hotel_info)
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))

In [17]:
# Add marker layer ontop of heat map


# Display figure